# Generated by Django 5.1.5 on 2025-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_remove_faq_language_remove_faq_question_bn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='translations',
        ),
        migrations.AddField(
            model_name='faq',
            name='translated_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
